# Site settings
title:          Project Euler
description:    "My solutions to solved Project Euler problems"
baseurl:        "/ProjectEuler"
url:            ""

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Mughil Pari
  email:        mughilan.muthupari@gmail.com

# Build settings
markdown:       kramdown
kramdown:
    math_engine: katex
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
